name: build-and-push
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}   # yeeho0o
          password: ${{ secrets.DOCKERHUB_TOKEN }}      # Access Token

      - name: Build & Push (latest + v5)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            yeeho0o/mlops-test:latest
            yeeho0o/mlops-test:v5
          cache-from: type=registry,ref=yeeho0o/mlops-test:latest
          cache-to: type=inline
          provenance: false   # (선택) 빌드킷 관련 에러 예방
