name: build-and-push
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}   # yekyung821
          password: ${{ secrets.DOCKERHUB_TOKEN }}      # Access Token
      - name: Build & Push (latest + v5)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            yekyung821/third-party-mlops:latest
            yekyung821/third-party-mlops:v5
          cache-from: type=registry,ref=yekyung821/third-party-mlops:latest
          cache-to: type=inline
